### ISSUE TITLE
Base Styling: Layout

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#10]
- [ ] add base styling for layout
-- should be responsive
-- decide: Grid? Flexbox? Box model?
-- ship something now and upgrade later?
- [ ] update Readme to include flexi information

**Comment by MelSumner** [comment]
After discussion with @rwwagner90 we have initially settled on Flexbox via flexi.

**Comment by rwwagner90** [comment]
@MelSumner was this completed?
