### ISSUE TITLE
Convert es-accordion to angle bracket component

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#116]
For the next iteration of these components, we should be using angle-bracket components. 

## To Do
- [ ] Convert es-accordion to be a template-only/angle bracket component
- [ ] Update documentation (in dummy app)

## Supporting Resources
- Video: [Angle Bracket Component Invocation in Ember.js](https://www.youtube.com/watch?v=KP_3MJTMpXI)
- Video: [Template-only components in Ember.js](https://www.youtube.com/watch?v=2DzV_0NAiUM)

**Comment by alexeykostevich** [comment]
@MelSumner , here are some links for convenience:
- [es-accordion source](https://ember-styleguide.netlify.com/docs/components/es-accordion)
- [es-accordion docs](https://ember-styleguide.netlify.com/docs/components/es-accordion)

Currently, `es-accordion` is not used in [ember-learn](https://github.com/ember-learn) projects.

It seems that the component is not a fully generic implementation of an accordion pattern and is designed for a specific use case:
<img width="677" alt="Screen Shot 2020-04-10 at 3 25 09 pm" src="https://user-images.githubusercontent.com/5205189/78965158-94555d80-7b3f-11ea-9e86-cfd80dd98123.png">

Taking into account that the team is updating the Ember.js design (https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md), would it make sense to re-implement it in a more generic way and make it consistent with the current design language?

I would be glad to help with this if we have the agreement on its design.

**Comment by MelSumner** [comment]
We want this component for use in projects that haven't been fully realized yet. If you want to take it on that would be great!! 👍

**Comment by alexeykostevich** [comment]
Ok let's do this! I'm starting working on a new `<EsAccordion />`.

**Comment by alexeykostevich** [comment]
@MelSumner , I've finished the draft version of a new `<EsAccordion />` component and will create the PR shortly.

Overall, the component will support:
- Single and multiple expanded panels simultaneously (configurable)
- Custom templates for a panel header
- Custom templates for a panel content
- DDAU-driven binding for expanded panels

Here is how its API looks like:

```handlebars
<EsAccordion
  @multi={{true}}
  @expanded={{value}}
  @expandedChange={{fn (mut value)}} as |accordion|
>
  <accordion.panel @name="panel-1" as |accordionPanel|>
    <accordionPanel.header @title="Panel 1 Header" />
    <accordionPanel.content>
      Lorem ipsum dolor...
    </accordionPanel.content>
  </accordion.panel>
  <accordion.panel @name="panel-2" as |accordionPanel|>
    <accordionPanel.header @title="Panel 2 Header" />
    <accordionPanel.content>
      Lorem ipsum dolor...
    </accordionPanel.content>
  </accordion.panel>
  <accordion.panel @name="panel-3" as |accordionPanel|>
    <accordionPanel.header>
      Panel 3 Header with custom content 🐹
    </accordionPanel.header>
    <accordionPanel.content>
      Lorem ipsum dolor...
    </accordionPanel.content>
  </accordion.panel>
</EsAccordion>
```

Here is how its design looks like:

<img width="817" alt="Screen Shot 2020-04-14 at 1 26 48 am" src="https://user-images.githubusercontent.com/5205189/79133250-0d2e1100-7def-11ea-8759-1d4d7ae138b7.png">

@MelSumner , @pichfl , please, let me know if you have any concerns about the features, API or design.

Thank you!

**Comment by alexeykostevich** [comment]
https://github.com/ember-learn/ember-styleguide/pull/301 removes not documented components including the legacy `<EsAccordion />`. So, it would be helpful to get it merged first before creating a PR for a new Octane version of the component.

**Comment by pichfl** [comment]
@alexeykostevich that looks good. I haven't done any design on this so far as it wasn't brought to my attention this would be a required module. Even so, it is an excellent application of the design styles I created 👍

**Comment by mansona** [comment]
@pichfl the reason this wasn't brought to your attention was that there is currently nowhere in any of our apps that actually uses an accordion 🙈 

We have something in the planned designs where we will need collapsible headers in the sidebar but I personally think that this ought to be implemented in the sidebar component and **not** in a separate accordion component.

@alexeykostevich you're right #301 does remove this and personally I think we shouldn't be adding it back until we have a known use case where we will need accordions in 2 places (i.e. other than just the sidebar component). I'm sorry I've had a super busy weekend so I missed the conversation starting back up on this issue, I really hope we don't end up with any wasted effort on this 🙈

**Comment by alexeykostevich** [comment]
@mansona , thank you for the details! No worries at all, I could be a little hasty with this 🙈

I totally agree that collapsible headers should be implemented in the `<EsSidebar />` component itself. So, `<EsAccordion />` is not needed for this functionality.

With regards to `<EsAccordion />` component, it is... ready (but without tests so far). However, I'm all for avoiding pushing unused code just for future needs. We know that this future might never comes but the maintenance cost will be there 🙂

So, let's do this. I've pushed the implementation of a `<EsAccordion />` into my forked repository. If we ever need this component, we can create a PR and merge it from here: https://github.com/ember-learn/ember-styleguide/compare/upgrade...alexeykostevich:feature/accordion

As I've mentioned, please, pay attention, that the implementation doesn't currently include tests -- I could add them when needed.

**Comment by MelSumner** [comment]
@alexeykostevich this looks great! I'll give it a review later today. In the meantime, if you wanted to add some tests (especially try out some ones that would confirm that the keyboard interactions work as expected) that would be great! Great job!

**Comment by alexeykostevich** [comment]
@MelSumner , I‘ll cover the component with tests (it’s actually my favourite part of work 🙃) when we decide to move forward with this.

As @mansona pointed out, there are no places in the new website design at this point where we might need an accordion. Taking this into account, it makes sense to put this on hold for now and return to this when needed.

Honestly, this will not hurt my inspiration: at the end we all want to get a clean up-to-date repository with necessary components. Frankly, currently that’s not always the case and avoiding unused code can be one of the solutions.

@MelSumner, @mansona , please, don’t worry about the effort (I learned a lot anyway!) and let me know about the final decision.

**Comment by MinThaMie** [comment]
Thanks for all your work. We might use it when it's needed again :)
