### ISSUE TITLE
Convert es-ulist to an angle bracket component

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#117]
For the next iteration of these components, we should be using angle-bracket components. 

## To Do
- [ ] Convert es-ulist to be a template-only/angle bracket component
- [ ] Update documentation (in dummy app)

## Supporting Resources
- Video: [Angle Bracket Component Invocation in Ember.js](https://www.youtube.com/watch?v=KP_3MJTMpXI)
- Video: [Template-only components in Ember.js](https://www.youtube.com/watch?v=2DzV_0NAiUM)

**Comment by hakubo** [comment]
I can take this one.

**Comment by mansona** [comment]
This is likely not needed any more because of #200 

Let me know if anyone has any questions :+1:
