### ISSUE TITLE
Convert es-button to angle bracket component

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#119]
For the next iteration of these components, we should be using angle-bracket components. 

## To Do
- [ ] Convert [es-button](https://ember-styleguide.netlify.com/docs/components/es-button) to be a template-only/angle bracket component
- [ ] Update documentation (in dummy app)
- [ ] Submit PR to the feature branch for angle bracket components ([feature/angle-bracket-components](https://github.com/ember-learn/ember-styleguide/tree/feature/angle-bracket-components))

## Supporting Resources
- Video: [Angle Bracket Component Invocation in Ember.js](https://www.youtube.com/watch?v=KP_3MJTMpXI)
- Video: [Template-only components in Ember.js](https://www.youtube.com/watch?v=2DzV_0NAiUM)

**Comment by alexeykostevich** [comment]
@MelSumner , `es-button` has been converted into a Glimmer component in https://github.com/ember-learn/ember-styleguide/commit/bd389faa1e3d0760a56ab0c3e276ee78d62d38e2 and its documentantion in https://github.com/ember-learn/ember-styleguide/commit/645fa88fd25a5b4571f31aa3f5ecfd54e5b309bb.

These changes are available in the [upgrade](https://github.com/ember-learn/ember-styleguide/tree/upgrade) branch.

So, it seems we could close the issue.

**Comment by MinThaMie** [comment]
Done :)
