### ISSUE TITLE
Component: es-note

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#12]
This component should support adding notes to guides and other bits of documentation. 

- [ ] It should support saying "Tomster says..." or "Zoey says..." (randomly)
- [ ] it should use either tomster or zoey's head image, depending on the title
- [ ] on small viewports, no image should be shown
- [ ] heading color is `$orange-darkest`

Screenshots: 
![image](https://user-images.githubusercontent.com/4587451/35700084-9906d4de-0757-11e8-8f61-34ee437114c2.png)

![image](https://user-images.githubusercontent.com/4587451/35700106-a85a2f08-0757-11e8-81ed-9dbe5f3bc3c1.png)

**Comment by pbishop16** [comment]
@MelSumner I can tackle this one!

**Comment by MelSumner** [comment]
@pbishop16 re: having the artwork for Zoey: @wifelette is going to obtain the necessary graphic, and I'll write up a separate issue for that so it won't block this story.

**Comment by pbishop16** [comment]
@MelSumner Got it. Sounds great. Thank you.
