### ISSUE TITLE
convert es-card to an angle bracket component

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#121]
For the next iteration of these components, we should be using angle-bracket components. 

## To Do
- [ ] Convert [es-card](https://ember-styleguide.netlify.com/docs/components/es-card) to be a template-only/angle bracket component
- [ ] Update documentation (in dummy app)
- [ ] Submit PR to the feature branch for angle bracket components ([feature/angle-bracket-components](https://github.com/ember-learn/ember-styleguide/tree/feature/angle-bracket-components))

## Supporting Resources
- Video: [Angle Bracket Component Invocation in Ember.js](https://www.youtube.com/watch?v=KP_3MJTMpXI)
- Video: [Template-only components in Ember.js](https://www.youtube.com/watch?v=2DzV_0NAiUM)

**Comment by alexeykostevich** [comment]
@MelSumner , `es-card` has been converted into a Glimmer component in https://github.com/ember-learn/ember-styleguide/commit/43537c9e5bfd3ac0290adea14fb9a9e6bac09489 and its documentation in https://github.com/ember-learn/ember-styleguide/commit/8481b8221bdb320f3e73820e1e8412c48a335ef6.

These changes are available in the [upgrade](https://github.com/ember-learn/ember-styleguide/tree/upgrade) branch.

So, it seems we could close the issue.

**Comment by MinThaMie** [comment]
Done :)
