### ISSUE TITLE
Typography - h1 needs more padding below

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-styleguide#13]
This is a suggestion that needs input from @MelSumner before anyone should work on it.

Currently
![screen shot 2018-02-04 at 10 56 18 pm](https://user-images.githubusercontent.com/16627268/35787799-df937e30-09fe-11e8-9f3d-519917865adc.png)

Proposed (8px padding below h1)
![screen shot 2018-02-04 at 10 57 19 pm](https://user-images.githubusercontent.com/16627268/35787815-efbbf256-09fe-11e8-8d41-7f6dd04326b4.png)

**Comment by oskarrough** [comment]
It looks like this can be closed? Screenshot from https://emberjs.com/ember-users/

![chrome_2018-04-13_16-29-24](https://user-images.githubusercontent.com/184567/38740449-e6796b9c-3f37-11e8-9269-b814f0eb039b.jpg)
