### ISSUE TITLE
Accessibility bugs on a button and links

### ISSUE THREAD

**Issue by alexpark90** [ember-learn/ember-styleguide#148]
There are three accessibility errors on a navbar toggle button and links on footer component. 
This issue originally opened in [ember-website](https://github.com/ember-learn/ember-website/issues/234), but fix is required on styleguide. 

Please see the screenshot below. 

![accessibility](https://user-images.githubusercontent.com/11951198/54572471-110a1c80-49be-11e9-98b4-06a87a0ff80f.JPG)

**Comment by alexpark90** [comment]
@jenweber , I have opened issue here. I would work on them and create pr soon if that is okay.

**Comment by acorncom** [comment]
Closed by the pr above
