### ISSUE TITLE
Component: es-card

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#15]
There are four possible items in this element: 
- an image
- a heading
- some text content
- a button (if used, es-button component)

Other criteria: 
- A border color should be able to be defined
- the border color should be transparent by default (a11y) 
- the image should have a border-radius of 2px if square
- the image should be allowed to be a circle
- the heading should be an h3 by default, but other tagNames should be acceptable to support semantic HTML

### The image: 
The image may be positioned:
- to the left of the text 
- centered on top of the text
- positioned to the right of the text 

### The heading: 
The heading may be positioned 
- above both the text and the image (if the element is horizontal)
- above the image and the text (if vertical) 
- below the image but above the text (if vertical) 
The heading should never be placed below all of the elements at once. 

### the Text: 
may be placed:
- next to the image (either to the left or to the right, depending on the placement of the media image). In this instance, the text should be automatically placed based on placement of the image, the user shouldn't have to place both.
- under the image

Sketch of possible iterations: 
![image](https://user-images.githubusercontent.com/4587451/36109146-7d2cdfde-1016-11e8-8f7e-e02cd7b5d1eb.png)

**Comment by MelSumner** [comment]
@SanthoshRaju91 we could probably control it with classes bound to boolean properties.

**Comment by Dan-Ste** [comment]
I'm going to work on it if it's ok

**Comment by Dan-Ste** [comment]
I'm thinking about make it composable component. Only can't come up with how to allow different heading types based on passed attributes

**Comment by Dan-Ste** [comment]
@MelSumner Is it ok to use BEM methodology for css classes?

**Comment by MelSumner** [comment]
I'm fine with that, although we should be cognizant that this might change in the future.

**Comment by mansona** [comment]
@MelSumner yes I would consider this done 👍

**Comment by pichfl** [comment]
We might have to look at this once more, the current implementation tries to achieve a little too much as described in #247

**Comment by MinThaMie** [comment]
It's an anglebracket component that meets all the needs, so I don't think we need this issue anymore
