### ISSUE TITLE
First link in navbar dropdowns appears "active" on dropdown open 

### ISSUE THREAD

**Issue by jneurock** [ember-learn/ember-styleguide#153]
**Notes:**
* By "active" I mean the appearance seems to indicate a hovered state or a state where the link matches the current route.
* I'm using Chrome 72 on macOS Mojave.

## Expected Behavior
When opening a navbar dropdown, only navbar dropdown links that are hovered or match the current route appear "active".

## Actual Behavior
When opening a navbar dropdown, the first link in the list appears "active". This confuses me. It makes me think this link matches the current route and discourages me from clicking on it, i.e., it appears clicking on it would have no effect.

I think this could potentially hinder the discovery of the guides for new visitors to Ember's homepage. When I click "Docs", the dropdown opens up and the first link is to the guides. In this case, the guides link appears "active" which makes me think I'm already on the guides page:

<img width="442" alt="Screenshot of the focused navbar from the Ember site" src="https://user-images.githubusercontent.com/326789/55672994-380f8c00-58a2-11e9-8f05-204f373fb4a4.png">

Upon inspection, it's clear this results from the first item receiving focus and the focus style matching the hover style for navbar dropdown links.

If I remove focus, the dropdown links appear as I would expect them:

<img width="443" alt="Screenshot of the non-focused navbar from the Ember site" src="https://user-images.githubusercontent.com/326789/55673011-6ab98480-58a2-11e9-974f-c71632eb0adb.png">

In the case above, it's clear to me I am not currently looking at the guides page.

## Steps to Reproduce
Click any dropdown in the navbar. Notice the first link appears "active".

<img width="603" alt="Sreenshot of navbar from the Ember Styleguide docs" src="https://user-images.githubusercontent.com/326789/55673066-04813180-58a3-11e9-88bc-616d706e2130.png">

**Comment by Charizard** [comment]
@jneurock Seems like this is being done on purpose [here](https://github.com/ember-learn/ember-styleguide/blob/master/addon/components/es-navbar/link/component.js#L102-L107). I am guessing for accessibility purposes? If so, @MelSumner should be able to clear this up.

**Comment by jneurock** [comment]
Thanks! I can see this was purposeful and I don't have any opinion on the JavaScript side of deliberately providing focus to the element. It's the CSS I'm looking at in this case. By making the first link appear "active", it confuses which page is currently being viewed, IMO.

**Comment by mansona** [comment]
So this component was originally designed to be as close as possible to https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html

It seems that when you click that navbar example it **doesn't** automatically select the first element, which means this is, in fact, a bug

**Comment by jneurock** [comment]
At some point, the styling issue I was having appears to have been fixed.

![image](https://user-images.githubusercontent.com/326789/69044680-a2220f00-09f5-11ea-9b0e-b4f32584ab20.png)
