### ISSUE TITLE
Component: es-header

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#16]
There isn't much to this component because it is going to contain other things. 

Requirements:
- [ ] header element
- [ ] 100% width of viewport
- [ ] should support background image
- [ ] should have a background color of ember-orange by default, but other colors should be able to be specified

**Comment by dbollinger** [comment]
I'm hoping to use this issue as my first foray into ember contributions 😬.  for the configurable background color requirement, what kind of usage are you looking for? predetermined class style themes like `{{es-header classNames='header-light'}}`, a property bound to the style attribute `{{es-header backgroundColor='#afafaf'}}`, or something else?

**Comment by MelSumner** [comment]
@dbollinger the idea is that we'll provide themes. Check out https://github.com/ember-learn/ember-styleguide/pull/48

**Comment by MelSumner** [comment]
@dbollinger just checking in on this. Anything I can do to help make this happen?

**Comment by dbollinger** [comment]
I think this one is still sort of blocked by #43

**Comment by MelSumner** [comment]
I think it's okay to implement w/o theme support. It can be used or not used. :)

**Comment by alexeykostevich** [comment]
The [es-header](https://github.com/ember-learn/ember-styleguide/blob/upgrade/addon/components/es-header.js) component has been implemented.

So, it seems the issue can be closed.
