### ISSUE TITLE
Fix toggle button on es-navbar component

### ISSUE THREAD

**Issue by ghislaineguerin** [ember-learn/ember-styleguide#166]
## Expected Behavior
- Toggle button should be hidden on resolutions larger than mobile
- Toggle button should expand the navigation menu when clicked

## Actual Behavior
- Toggle button is visible at all resolutions
- Toggle button does not expand or collapse the navigation menu

## Steps to Reproduce
(to be added)

**Comment by mansona** [comment]
Closed in #227
