### ISSUE TITLE
Component: es-accordion

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#17]
## Acceptance Criteria:
- [ ] responsive
- [ ] when one panel is open, the other ones collapse automatically
- [ ] add aria-expanded to the control element (if the collapsible element is closed by default, the attribute should be `aria-expanded="false"`.)  See: https://www.w3.org/TR/wai-aria-practices-1.1/#accordion

### Keyboard Interactions:
- [ ] Enter or Space: 
- When focus is on the accordion header for a collapsed panel, expands the associated panel. If the implementation allows only one panel to be expanded, and if another panel is expanded, collapses that panel.
- When focus is on the accordion header for an expanded panel, collapses the panel if the implementation supports collapsing. Some implementations require one panel to be expanded at all times and allow only one panel to be expanded; so, they do not support a collapse function.
- [ ] Down Arrow: If focus is on an accordion header, moves focus to the next accordion header. If focus is on the last accordion header, either does nothing or moves focus to the first accordion header.
- [ ] Up Arrow: If focus is on an accordion header, moves focus to the previous accordion header. If focus is on the first accordion header, either does nothing or moves focus to the last accordion header.
- [ ] Home (Optional): When focus is on an accordion header, moves focus to the first accordion header.
- [ ] End (Optional): When focus is on an accordion header, moves focus to the last accordion header.
- [ ] Control + Page Down (Optional): If focus is inside an accordion panel or on an accordion header, moves focus to the next accordion header. If focus is in the last accordion header or panel, either does nothing or moves focus to the first accordion header.
- [ ] Control + Page Up (Optional): If focus is inside an accordion panel, moves focus to the header for that panel. If focus is on an accordion header, moves focus to the previous accordion header. If focus is on the first accordion header, either does nothing or moves focus to the last accordion header.

## Pieces of component: 
- "header" (not header element) 
- body (block yield)
- footer

## Screenshots: 
Closed:
![image](https://user-images.githubusercontent.com/4587451/36110489-a974acd0-101a-11e8-877f-d18acf94aa60.png)

Open: 
![image](https://user-images.githubusercontent.com/4587451/36110517-bc18ff44-101a-11e8-886e-d8bf7bb28294.png)

**Comment by pbishop16** [comment]
@MelSumner Would like to tackle this one.
