### ISSUE TITLE
Component: es-blog-heading

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#19]
There are three types of blog posts: 
- regular
- syndicated (written elsewhere but re-posted here)
- guest post

The CSS for this component can be taken from the current website, which reflects the desired styles. 

On the summary page: 
![image](https://user-images.githubusercontent.com/4587451/36462214-b1f2103c-1687-11e8-90f5-eca6a91d4be0.png)

On the individual post page:
![image](https://user-images.githubusercontent.com/4587451/36462226-bf159e96-1687-11e8-941b-6fb5a69b7427.png)

Be sure to follow the semantic markup- this can be achieved by examining the rendered markup on the current blog (emberjs.com/blog).

**Comment by MelSumner** [comment]
Assigning myself to this because the updates to the current Ember blog will force an update to this component.

**Comment by pbishop16** [comment]
@MelSumner I will tackle this one.

**Comment by MelSumner** [comment]
Thank you @pbishop16 !
