### ISSUE TITLE
SCSS Linter

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#2]
Need to write SCSS linter rules that will enforce specific CSS code standards. 

- lowercase class names
- no IDs
- possible to enforce naming structure for color variables? if so, colors should be named like this if they exist: 
-- $color
-- $color-darker
-- $color-darkest
-- $color-lighter
-- $color-lightest
- properties should be in alphabetical order
- css should be mobile-first. I.E.
```
.my-button {
    width: 100%;
    padding: 0.1em;
    border: 1px solid $blue;
    @media screen and (min-width: 768px) {
      width: 50%;
    }
    @media screen and (min-width: 992px) {
      width: 25%;
    }
}
```
- color variables should only be in a _variables.scss file. 
- headings should only be declared once.

**Comment by rwwagner90** [comment]
@MelSumner I could pull in ember-cli-stylelint, but not sure which of these rules exist already. Should I give it a shot?

**Comment by MelSumner** [comment]
Resolved!
