### ISSUE TITLE
[redesign] Move to Inter font family

### ISSUE THREAD

**Issue by pichfl** [ember-learn/ember-styleguide#222]
The latest iteration of the design made for the new website RFC contains a new font family to represent the professional look and feel of the Ember.js website. It is called [Inter](https://rsms.me/inter/), is free and open source and crafted with special care for screen based UI.

Since we are nearing launch, we need to replace the currently used Open Sans with the appropriate cuts of Inter across the website.

**Comment by mansona** [comment]
closed in #225
