### ISSUE TITLE
Implement (and document) the "flip" order helper for our grid

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#237]
I discussed this with @pichfl a while ago and it was a solution to make sure that we could have the correct ordering of text and images on mobile when using grid

the best example is the new homepage in the "Ember Ecosystem" section: https://deploy-preview-451--ember-website.netlify.com/

If you view this on mobile it will be in the order: 

- Text
- Image
- Image
- Text
- Text
- Image 

but it should be alternating

**Comment by MelSumner** [comment]
Since order matters for accessibility, we should ensure that DOM order stays the same whether on mobile or desktop.

**Comment by mansona** [comment]
This is now done, you can see it in place on the landing page that the DOM order is always the same for the batteries included but the visual order is different 👍
