### ISSUE TITLE
Link color in text is not meeting color-contrast criteria

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#241]
The text link color does not have enough contrast, and is missing underlines. Also, the font-size is too small. 

To fix: 
- [ ] increase the color contrast of links
- [ ] ensure that the font size is 18px and line height is 1.5 for paragraph text
- [x] add underlines back in to the links in the paragraph text

**Comment by pichfl** [comment]
- the link color for links in regular text is yet to be defined
- the (previously approved) design calls for a base font size of 15px and we enforce usage of `rem` based units, which in turn allows users to scale as necessary. 
- yes, please. Underlines should always be the default for links in prose.

In short, I need to prepare additional design to ensure that we provide links that fit and match all necessary criteria.

**Comment by MelSumner** [comment]
I don't remember approving a base font size of 15px- I know I wouldn't have approved that. At the minimum 16px, and ideally 18px has been my approach for years (esp for a11y reasons).

**Comment by pichfl** [comment]
See https://share.goabstract.com/963cd6c9-6198-42e1-997c-eb0705bff1d8?mode=build&sha=48031bc1d5bd8cf9e9be5451af4450def9b69509

I don't think any starting font size is inaccessible unless it is fixed and we are using a completely relative approach, so fonts can be scaled using the features baked into any browser, which at least to me is the more important factor than the base size. Not to mention that most browsers today to a full page zoom anyway, which works even for fixed sizes. 

Changing the font sizes is possible, but should require an additional day of design work as I will have to adjust line heights across the document and most likely change the vertical rhythm of the page including all offsets to follow suit, as just increasing the size would bring imbalance to the design.

**Comment by MelSumner** [comment]
I'm very sorry, I don't know how I missed it, but the recommended base font size for A11y is 18px and 1.5 (unitless) line height. I'm typically willing to go down to 16px but not any smaller than that. Even if it needs a little re-work, it will be worth it.

**Comment by pichfl** [comment]
I did provide fine tuned line-heights for all available font sizes and provided matching CSS custom properties. 

A line-height of 1.5 is always a good start, but every font requires fine tuning for readability beyond that. In our case, moving from 15px to 16px might require a line-height shift from 24px to 25px (1.5625) or 26px (1.625) to make the line spacing look and read good for the x-height of the Inter font. Of course this will never be perfect when zoomed in or out, but we can at least consider proper spacing for the default state. 

I'll provide updated mockups and necessary variables by Thursday.

**Comment by mansona** [comment]
Note: the only remaining task on this issue is to fix the link styling on `dark` backgrounds

**Comment by mansona** [comment]
Fixed in #260
