### ISSUE TITLE
Separate cards from figures

### ISSUE THREAD

**Issue by pichfl** [ember-learn/ember-styleguide#247]
As the design progressed, it became obvious, that the Card component tries to accomplish to many things at once. 

I therefore propose having an `<EsCard />` component and another `<EsFigure />` component, which both have different use cases.

### Cards

Cards should behave depending on the available container space. Orienting their content horizontally insider larger containers (think three desktop grid columns wide ore more) and smaller inside narrow ones (think two desktop grid columns or less). There is a very clever way of solving this to be found in the [Every Layout (paid)](https://every-layout.dev/layouts/switcher/), which I can provide.

Cards should be used if you have an image with accompanying text which form a unit that represents a summary of the content they reference. Therefore, the whole card should be a link. Cards are interactive and do have a hover state and an active state.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/194641/68973930-c0b6b900-07ef-11ea-9c80-7eea0c2d2471.png">

### Figures

Figures are images that have a caption. Both the image and the caption can be linked or in case of the caption contain multiple links. Figures to not have a hover or active state on their own and are merely layout blocks. 

We could abstract some of the styling into a component to make it easy to re-use the design found on the Sponsors or Mascots pages.

<img width="286" alt="image" src="https://user-images.githubusercontent.com/194641/68974004-f3f94800-07ef-11ea-87db-c5eb0a518fd9.png">

**Comment by alexeykostevich** [comment]
Thank you for the great summary, @pichfl ! Great job! 🚀

According to the description, `<EsCard />` should describe the summary of referenced content and represent a single link.

The existing`<EsCard />` does not represent a link. Instead, it contains a link (represents summary) or multiple links (represents a group of references).

<img width="1022" alt="Screen Shot 2020-04-16 at 11 46 04 pm" src="https://user-images.githubusercontent.com/5205189/79464509-7b681300-803d-11ea-877e-e39e20e234cc.png">

Would be correct to say that the places, where there are multiple links in a card, should be converted to `EsFigure`?

**Comment by alexeykostevich** [comment]
If my assumption above is correct, here are the places where could use these components.
 
# Cards

**Place 1 ([Homepage](https://emberjs.com/)):**
<img width="999" alt="Screen Shot 2020-04-16 at 11 45 51 pm" src="https://user-images.githubusercontent.com/5205189/79464498-7905b900-803d-11ea-8dcb-40df70293797.png">

**Place 2 [Homepage](https://emberjs.com/):**
<img width="1014" alt="Screen Shot 2020-04-16 at 11 46 18 pm" src="https://user-images.githubusercontent.com/5205189/79464513-7c994000-803d-11ea-926c-f73eadf93e05.png">

**Place 3 [Guides](https://guides.emberjs.com/release/):**
<img width="658" alt="Screen Shot 2020-04-17 at 12 14 32 am" src="https://user-images.githubusercontent.com/5205189/79466867-7c4e7400-8040-11ea-80a1-6b6aa687020d.png">

# Figures

**Place 1 ([Homepage](https://emberjs.com/):**
<img width="1022" alt="Screen Shot 2020-04-16 at 11 46 04 pm" src="https://user-images.githubusercontent.com/5205189/79464509-7b681300-803d-11ea-877e-e39e20e234cc.png">

**Place 2 ([Editions](https://emberjs.com/editions))**:
<img width="359" alt="Screen Shot 2020-04-16 at 11 46 47 pm" src="https://user-images.githubusercontent.com/5205189/79465712-12819a80-803f-11ea-9569-deb07055e19e.png">

**Place 3 ([Mascots](https://emberjs.com/mascots))**:
<img width="1008" alt="Screen Shot 2020-04-16 at 11 47 53 pm" src="https://user-images.githubusercontent.com/5205189/79465719-13b2c780-803f-11ea-9398-f9237b9ea69f.png">

**Place 4 ([Sponsors](https://emberjs.com/sponsors))**:
<img width="1010" alt="Screen Shot 2020-04-16 at 11 48 10 pm" src="https://user-images.githubusercontent.com/5205189/79465729-14e3f480-803f-11ea-8f14-028703d51a43.png">

**Place 5 ([Deprecations](https://deprecations.emberjs.com/))**:
<img width="685" alt="Screen Shot 2020-04-17 at 12 07 46 am" src="https://user-images.githubusercontent.com/5205189/79466471-fc280e80-803f-11ea-83a8-fde59c02b30f.png">

**Place 6 ([Who uses Ember](https://emberjs.com/ember-users))**:
<img width="1010" alt="Screen Shot 2020-04-17 at 12 10 49 am" src="https://user-images.githubusercontent.com/5205189/79466477-fd593b80-803f-11ea-9f71-d6abc27357bb.png">

**Place 7 ([Team](https://emberjs.com/teams))**:
<img width="931" alt="Screen Shot 2020-04-16 at 11 58 48 pm" src="https://user-images.githubusercontent.com/5205189/79465735-16152180-803f-11ea-95de-8f154f101e6d.png">

**Comment by pichfl** [comment]
We made some distinction here, that was made after this issue was created. There are now horizontal cards (which have a single link that spans the whole card through some css trickery for a11y reasons) and the vertical ones, which can contain multiple links. 

The vertical ones (found on the homepage) are not equal to figures as the content does not describe the image like a caption would do for a figure element. 

All other places but the team are well spotted. the team page has a potential redesign that uses vertical cards as well to add some consistency.

**Comment by pichfl** [comment]
I'm actually not sure if this issue should remain open, all cases were covered using the classes and components available in the style guide. @mansona what do you think?

**Comment by MinThaMie** [comment]
Let's close this if it's no longer needed and when we decide it's needed again, we can reopen :)
