### ISSUE TITLE
Button size variations don't seem to be working

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-styleguide#248]
## Expected Behavior
I wanted to be able to use small and large buttons that I used in previous versions.

## Actual Behavior
Only one size was available.

## Steps to Reproduce
If you run the latest website-redesign-rfc branch and visit the buttons page, you can see the buttons all look the same

**Comment by pichfl** [comment]
Thanks @MelSumner for pointing me to this.

@jenweber The redesign does not feature buttons in multiple sizes yet. Can you provide me with an example page where they are necessary?

**Comment by mansona** [comment]
@jenweber this was a bit of an issue with the documentation for the longest time 🙈 I have gone through the docs and made sure it only shows examples for things that are actually working now https://deploy-preview-145--ember-styleguide.netlify.com/components/button

If we need button size variations we can open a different issue 👍
