### ISSUE TITLE
Spacing helpers do not override in all situations

### ISSUE THREAD

**Issue by pichfl** [ember-learn/ember-styleguide#254]
## Expected Behavior

`p-*` and `m*` should allow overriding spacing on `.container`.

## Actual Behavior

They don't

## Steps to fix

Move includes for both helpers to the end of the `addon.css` file so they can properly override in all situations.

**Comment by alexeykostevich** [comment]
The issue has been fixed in https://github.com/ember-learn/ember-styleguide/commit/8fc5677d786ac309e58c8bfd52d49076600ccbd7 by @mansona .

So, we can close the issue.
