### ISSUE TITLE
es-button styling is broken when used on anchors

### ISSUE THREAD

**Issue by pichfl** [ember-learn/ember-styleguide#255]
## Expected Behavior

Applying `.es-button` to a `<a>` should make it look like a button. 

## Actual Behavior

It looks like a link, but with the button spacing applied.

## Steps to fix

Ensure the correct pseudo-states are applied to `.es-button`. `:link, :visited, :active` all need to have the correct background.

**Comment by alexeykostevich** [comment]
The issue has been fixed within https://github.com/ember-learn/ember-styleguide/pull/257 and can be closed.
