### ISSUE TITLE
Declare mono font family as a css variable

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-styleguide#256]
## Expected Behavior
Mono font family should be declared as a css variable

## Actual Behavior
It is declared inline

**Comment by mansona** [comment]
Hey @sivakumar-kailasam I'm about to merge the PR that fixes this, but if you're using the variable upstream you need to be careful. The way that the build is working it will make sure that the vendor.css has the right fallbacks for browsers that don't support CSS variables but we're not automatically doing anything with the consuming app's CSS. We will need to discuss your pipeline and use of these variables to make sure that they are working the way that you are expecting 👍
