### ISSUE TITLE
update CSS to appropriately render button groups/buttons on different screen sizes

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#283]
This is a continuation of a conversation on the new redesign https://github.com/ember-learn/ember-website/pull/555#discussion_r378180714

essentially we are using margins on buttons on the homepage but when they wrap they are no longer centred properly.

We will probably need some way to put buttons into a "button row" or "button group" that deals with the behaviour correctly 👍

**Comment by nickschot** [comment]
Either that or responsive margin utilities (like tailwind has). The first is definitely simpler if they're not going to be used elsewhere though.

**Comment by MelSumner** [comment]
it should just be a media query. We shouldn't need util classes for this. <3
