### ISSUE TITLE
EsPageHeader component should not render empty elements

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#284]
## Expected Behavior
I didn't want to use the elements provided by the component because I wanted greater control over the line breaks. So I used the component as a block component. I did not expect it to still render the h1 and p elements while empty. 

## Actual Behavior
The `h1` and `p` tags rendered even though they were empty. 

Screenshot:
![image](https://user-images.githubusercontent.com/4587451/74359603-3566a880-4d89-11ea-94b4-6da56677e931.png)

**Comment by mansona** [comment]
fixed in https://github.com/ember-learn/ember-website/pull/561
