### ISSUE TITLE
styleguide rendering issue

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#286]
## Expected Behavior
the content should stay behind the menu when it is open

## Actual Behavior
the content overlaps the menu when the menu is open 

Screenshot: 
![image](https://user-images.githubusercontent.com/4587451/74379008-905dc700-4dac-11ea-968c-edde24323d55.png)

**Comment by alexeykostevich** [comment]
@mansona , just for sharing... I've created a PR https://github.com/empress/field-guide-default-template/pull/8, which addresses this issue.
