### ISSUE TITLE
Remove isDevelopingAddon when publishing the addon

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-styleguide#289]
When the redesign branch of this addon is published, it ships with the `isDevelopingAddon` hook set to return `true`. 

The template errors from this addon show up in the consuming app's test suite as a result of this. Can we publish the package with that removed or driven through any config that defaults to false when not set?

**Comment by rwjblue** [comment]
TBH, we shouldn't need to have that hard coded to true at all (when locally developing it is already true).

**Comment by mansona** [comment]
Fixed in #296
