### ISSUE TITLE
analysis: es-navbar component

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#29]
- review es-navbar component
- write tests that are accurate
- ensure code is written to pass the tests; update component if necessary
- ensure all tests pass

**Comment by terrancebryant** [comment]
@MelSumner I would like to take a crack at this

**Comment by terrancebryant** [comment]
@mansona Sounds good let me know what i can do to help

**Comment by MelSumner** [comment]
@terrancebryant would you be willing to look at #77 and see what you think? It would be super helpful! If you wanted to propose an alternate approach to consider that would be great too!

**Comment by MinThaMie** [comment]
Since #77 is merged I think we're okay on this issue :)
