### ISSUE TITLE
Component: es-navbar

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#3]
**Context:** 
Help is needed to complete the work started on the es-navbar component in this addon. This is the navigation component that is intended to be used on the emberjs.com website, along with other "Ember Family" websites (ember-cli, fastboot, etc). 

**Criteria**
- [ ] mobile-first responsive web design (RWD)
- [ ] use semantic HTML(5)
- [ ] should (also) be keyboard-only navigable
- [ ] should support sub-menus (at least one level deep)
- [ ] should work in Chrome, Firefox, Safari (current ver. -1), IE(11, and Edge

**Comment by rwwagner90** [comment]
@MelSumner are there designs for this? Is it intended to copy the navbar from https://emberjs.com/ or should it be something different?

**Comment by MelSumner** [comment]
@rwwagner90 yes, it should do that.

**Comment by MelSumner** [comment]
continuing the work on this today (02/18/18)

**Comment by MelSumner** [comment]
Thank you for doing this, @rwwagner90 !

**Comment by rwwagner90** [comment]
You're welcome. Thanks for all your help @MelSumner!
