### ISSUE TITLE
Add EsNote back to the styleguide

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#302]
In order to get the 4.0 release out the door we had to temporarily remove the `<EsNote />` component from the redesign branch of the styleguide https://github.com/ember-learn/ember-styleguide/pull/301

We need this to be re-implemented for the Guides and Deprecations app

**Comment by alexeykostevich** [comment]
@mansona , could I help with this issue? If yes, please, let me know whether any major changes in the design or functionality of `<EsNote />` are expected comparing to its current version: https://ember-styleguide.netlify.app/docs/components/es-note

**Comment by mansona** [comment]
Sorry I should have closed this 🙈 it is being addressed by #306
