### ISSUE TITLE
Tracking Issue: Applying Website Redesign to Ember Learn Apps

### ISSUE THREAD

**Issue by jayjayjpg** [ember-learn/ember-styleguide#313]
With the [latest release of the website redesign via ember-styleguide](https://github.com/ember-learn/ember-styleguide/releases/tag/v4.0.0), the community is now able to apply the latest design changes to not only the [Ember website](https://github.com/ember-learn/ember-website/pull/361), but also to all other remaining Ember Learn apps.

Edit: the tracking of the work remaining on the redesign will be in the Initiative board https://github.com/orgs/ember-learn/projects/39 and all of the linked sub-boards there

You can also see a summary of the plan moving forward [on the Ember blog](https://blog.emberjs.com/2020/04/26/update-ember-website.html)

## Outstanding projects for the redesign

- [ember-blog](https://github.com/ember-learn/ember-blog)
- [guides-source](https://github.com/ember-learn/guides-source)
  - Work is actually on the [guidemaker-ember-template](https://github.com/ember-learn/guidemaker-ember-template)
- [ember-api-docs](https://github.com/ember-learn/ember-api-docs)
- [deprecation-app](https://github.com/ember-learn/deprecation-app)
- [ember-help-wanted](https://github.com/ember-learn/ember-help-wanted)
- [cli-guides](https://github.com/ember-learn/cli-guides)

## How-to for applying the redesign

Edit: updating to 3.16 is not necessary as part of the redesign 👍 

### Guidemaker Apps

This includes the CLI Guides, Ember Guides (guides-source) and Contribution Guides

- Install the latest beta release of guidemaker-ember-template
- check if tests & linters still run
- optional: update any remaining styles for the target app according to the brand colors from ember-styleguide

### Custom Ember apps

- (for non Guides apps only): install the latest release of ember-styleguide
- check if tests & linters still run
- optional: update any remaining custom styles which are not covered by components from the styleguide already according to the brand colors from [the styleguide color palette](https://ember-styleguide.netlify.app/concepts/colors)

## Tasks

Sign up for a task by finding an issue in the respective Github Project boards and commenting on that issue or join us on the [#dev-ember-learning channel on the Ember Discord](https://discordapp.com/invite/emberjs) for more info!

### Ember Blog

- See also https://github.com/orgs/ember-learn/projects/15

### Guides

https://github.com/orgs/ember-learn/projects/45

### Ember API Docs

https://github.com/orgs/ember-learn/projects/41

### Deprecations App 

https://github.com/orgs/ember-learn/projects/44

### Help Wanted

https://github.com/orgs/ember-learn/projects/42

### CLI Guides

https://github.com/orgs/ember-learn/projects/40

---

**Comment by mansona** [comment]
👋 @jayjayjpg I have updated the description of this issue (as we discussed) to remove any information that wasn't correct in case people are pointed in the wrong direction.

Now based on our conversation, we talked about not duplicating the organisation of the project. Would you mind if I closed this issue? or do you see there being a benefit in keeping this information around? If so then I would love to understand more of the benefit and we can probably make this more useful for the project generally 👍

**Comment by jayjayjpg** [comment]
@mansona Can we put the issues that I mentioned in this tracking issue and which are still relevant for applying the website redesign onto the project board, so other contributors we already talked with and me have a visual cue on what I can work on next? I agree that we shouldn't duplicate content and when we moved all of the todos over there, and created the documentation from the ticket above in another way ticketwise, I think this is good to close!

If the respective tickets exist on the board already, and I just missed them, can you point me into the right direction?

**Comment by mansona** [comment]
@jayjayjpg so for each of the projects there were 3 issues listed: 

- update to 3.16 
- set up a preview app for the new redesign
- "apply the redesign" issues

We discussed that the first one isn't relevant any more 🎉 I closed all the preview app issues because they were done (they were already done because each of the apps are using netlify 🎉 ) and I haven't done anything about the third issue type yet 🤔 

I started a discussion on https://github.com/ember-learn/cli-guides/issues/175 so once we figure that out then it will cover all of the issues that used to be on this tracking issue 👍

**Comment by mansona** [comment]
We are tracking this work in https://github.com/orgs/ember-learn/projects/39 now 👍
