### ISSUE TITLE
contact details in footer

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#336]
This was originally brought up in a learning team meeting: https://github.com/emberjs/core-notes/blob/master/learning-team/2020-08/2020-08-20.md#new-wcag-coming-up-ms-5min

We want to add the sentence: 

If you want help you can [contact us by email](mailto:email), [open an issue](https://github.com/ember-learn/ember-website/new/issue?body=camefrom=window.location), or get realtime help by [joining the Ember Discord](https://discord.com)

The open an issue link should: 
- [x] default to ember-website
- [x] be dynamic based on the "contribute to this repo" link that was passed
~~- include the "submitted from URL" in the body of the issue if possible~~ moved to https://github.com/ember-learn/ember-styleguide/issues/346

**Comment by ecodata1** [comment]
Hi @mansona, I'm interested to help, this would be my first issue.

Would this be best as a new sub-component e.g <EsFooterHelp>? I could create a basic component template PR to try things out. (May need help with github integration/ dynamic links)

What is the contact email address?

**Comment by fozy81** [comment]
Hi @mansona, I'm interested to help, this would be my first issue.

Would this be best as a new sub-component e.g EsFooterHelp.hbs ? I could create a basic component template PR to try things out. (May need help with github integration/ dynamic links)

What is the contact email address?

**Comment by fozy81** [comment]
Added a PR - just a work in progress, but hopefully helps a bit. The url is a component attribute not dynamic based on the window location. I'm not quite sure the best way to do that.

**Comment by mansona** [comment]
hey @fozy81 sorry I took the weekend off so I didn't see this until now 😂 

I'll comment on the PR with some suggestions 👍
