### ISSUE TITLE
Change "hamburger" icon on the `<EsHeader />` component the word "Menu" or "Nav"

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#363]
This is designed to make it clearer for users to know what that particular "hamburger" menu is supposed to be

**Comment by fozy81** [comment]
Hi @mansona - I'd like to try fixing this issue. 

I've got a question about overflow/hidden text in the current menu hamburger: 

Currently  the hamburger button has this text inside it:
 `{{if this.expanded "Hide" "Show"}} Site Navigation`\
But this text is hidden from display by the css: 
`overflow: hidden; text-indent: -999rem;` (?)

I could insert 'Menu'  text into the menu button and remove the hamburger svg but do we still need the `{{if this.expanded "Hide" "Show"}} Site Navigation` text as well? For screenreaders? :thinking:

**Comment by fozy81** [comment]
I'm think replacing the hidden `Site Navigation` text should go into aria? for example:
 `aria-label="{{if this.expanded "Hide" "Show"}}  screen reader only label"`

**Comment by mansona** [comment]
I'm going to close this issue now as a "won't fix" 

I explain more about this in the comment that closed the PR https://github.com/ember-learn/ember-styleguide/pull/397#issuecomment-885045337 

sorry again for the confusion!
