### ISSUE TITLE
Component: es-graphic

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#37]
This component can be used in places where there is a short list of items that would be made more interesting if they were interactive graphics.

For example, this: 
![image](https://user-images.githubusercontent.com/4587451/36462315-48e57556-1688-11e8-928e-a4a4937fbde1.png)

Can become this: 
![image](https://user-images.githubusercontent.com/4587451/36462329-5fb4dab0-1688-11e8-8117-033050f565be.png)

Which becomes this on hover/focus:
![image](https://user-images.githubusercontent.com/4587451/36462341-699ee0c0-1688-11e8-9876-6d2c3bbeddef.png)

See https://codepen.io/melsumner/pen/0b6bb9796cdd8f8c70ab942a2ba6d5d7 for a live code sample. 

Acceptance criteria:
- [ ] background should be $orange & $orange-darken on hover/focus
- [ ] text should be a customizable property
- [ ] text should be positioned at the bottom of the graphic
- [ ] three items should be equally spaced across the smallest viewport (using Flexbox)

**Comment by serenaf** [comment]
@MelSumner Will take a stab at this this week :)

**Comment by MelSumner** [comment]
Awesome! Thank you @serenaf !!!

**Comment by MelSumner** [comment]
@serenaf is there anything I can do to help this move forward?

**Comment by serenaf** [comment]
@MelSumner I will pick this up Mel in a weeks time 🎉 (on holidays for a week next week). I will catch up with you when i am back?

**Comment by MinThaMie** [comment]
This component does not exist and we might not need it right now. We'll create a new issue to pick it up if we need it
