### ISSUE TITLE
Move the notification banner to the styleguide

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-styleguide#371]
**Note, this issue is reserved for EmberConf contributors workshop. Please volunteer for the issue if you are participating in the workshop.**

## Description

We have a [ember website banner component](https://github.com/ember-learn/ember-website/blob/1857017bc86beaacba045a0aefac8dec9e3a1a1c/app/templates/application.hbs#L5) that we want to make generalizable and share with other Ember apps.

![Screen_Shot_2021-03-29_at_8_51_39_AM](https://user-images.githubusercontent.com/6305935/112839595-6167ea80-906c-11eb-9256-872045f7c019.png)

To-do:
- Copy the navigation banner from https://github.com/ember-learn/ember-website into the styleguide
- Add documentation so that it shows up with the other com

ponents when you run the styleguide app

## Supporting information

This is part of a project to update the Ember Guides to use the same styles as we use on emberjs.com. As much as possible, we want CSS and components to be part of [ember-styleguide](https://github.com/ember-learn/ember-styleguide) so they can be easily shared across projects. You can see the full project board at https://github.com/orgs/ember-learn/projects/45

**Comment by amyrlam** [comment]
Hey I can work on this, just talked to @jaredgalanis

**Comment by amyrlam** [comment]
From meeting: should address BLM, survey, EmberConf.

https://github.com/ember-learn/ember-website/pulls?q=is%3Apr+is%3Aclosed+banner

**Comment by fozy81** [comment]
I'll try taking on this issue after agreeing with @amyrlam to pick it up
