### ISSUE TITLE
Move the ProgressBar into styleguide

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-styleguide#374]
**Note, this issue is reserved for EmberConf contributors workshop. Please volunteer for the issue if you are participating in the workshop.**

## Description

The blog has a loading animation at the top of the page. You can see this loader bar if you click "older articles" at the bottom of the page a couple times. We'd like to use this in the guides too, so it would be great to add to the `ember-styleguide`.

![Screen_Shot_2021-03-18_at_10_47_57_AM](https://user-images.githubusercontent.com/6305935/111645801-75435f00-87d7-11eb-9640-af2ddd4d385a.png)

To-dos:
- [ ] Copy the `ProgressBar` component and `Progress` service from the blog, both of these are located in [empress-blog-ember-template](https://github.com/ember-learn/empress-blog-ember-template) into the [ember-styleguide](https://github.com/ember-learn/ember-styleguide).
- [ ] Add documentation to the [docs section of the `ember-styleguide`](https://github.com/ember-learn/ember-styleguide/tree/f90c7d5aa956c0a7e0076901a53116af8164994f/docs) so that it shows up with the other components when you run the styleguide app.
- [ ] If you have time, please make sure the progress bar works well together with the [ember website banner component](https://github.com/ember-learn/ember-website/blob/1857017bc86beaacba045a0aefac8dec9e3a1a1c/app/templates/application.hbs#L5) in the ember website (which makes use of `ember-styleguide`) by adding the progress bar to the [ember website](https://github.com/ember-learn/ember-website/). 

## Supporting information

This is part of a project to update the Ember Guides to use the same styles as we use on emberjs.com. As much as possible, we want CSS and components to be part of [ember-styleguide](https://github.com/ember-learn/ember-styleguide) so they can be easily shared across projects. You can see the full project board at https://github.com/orgs/ember-learn/projects/45

**Comment by afzal273** [comment]
I'll work on this one

**Comment by jaredgalanis** [comment]
Hey @afzal273, just checking in on this one. Did you still want to take it on or were you only thinking of working on it during ember conf workshop? No worries at all either way!

**Comment by afzal273** [comment]
Thanks for checking in and the reminder. I'll still take it on.
