### ISSUE TITLE
convert ember-styleguide to use co-located components

### ISSUE THREAD

**Issue by jaredgalanis** [ember-learn/ember-styleguide#378]
**Note, this issue is reserved for EmberConf contributors workshop. Please volunteer for the issue if you are participating in the workshop.**

Currently the components in ember-styleguide are not co-located with their templates. 

https://github.com/ember-learn/ember-styleguide/tree/master/addon/components
https://github.com/ember-learn/ember-styleguide/tree/master/addon/templates/components

We should move to a co-located style so that component JavaScript files and hbs templates are co-located together.

**Comment by afzal273** [comment]
I'll take this one

**Comment by jaredgalanis** [comment]
@afzal273, I'm going to work on this one with @hannakim91, if that's okay with you.

**Comment by afzal273** [comment]
Sure sounds good, sorry I wasn't able to get to it yet.
