### ISSUE TITLE
es-sidebar doesn't have a min with

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#379]
I just tried to use the new es-sidebar in the Gudiemaker redesign and it was super small. It currently has a `width` set but I needed to hard-code a `min-width` to make it actually expand properly.

I'm not exactly sure why it needs this 😂  but it works 🤷 

Any thoughts @nickschot ?

**Comment by nickschot** [comment]
if I remember correctly in our current design the sidebar container imposes the correct width. What's different about the guidemaker setup? Have some code you can show me?

**Comment by mansona** [comment]
Yes indeed! You will be able to see it in the preview app for this: https://github.com/ember-learn/guidemaker-ember-template/pull/71

**Comment by nickschot** [comment]
So the blog seems to be using an older implementation right now (which I think is correct, we haven't upgraded it yet). The reason the blog works is that it uses disiplay grid. The current implementation in styleguide uses flexbox. What seems to be missing is an explicit width for the non-sidebar content. E.g. adding `width: 100%;` to 
```
.sidebar-container > :not(.es-sidebar):not(.es-sidebar-toggle)
```
should fix it (for the > 768px media query).

**Comment by mansona** [comment]
Just keeping a note here related to the issue: We discussed this today on a call and it seems to be related to the fact that we used Flexbox to implement this feature in the styleguide but actually we rely on Grid to impelment it in the Ember blog (where this feature originally came from)

The proposed fix is to just ditch the use of Flexbox for this feature and use Grid in the same way that we did originally 👍

**Comment by nickschot** [comment]
Issue was slightly different, the easier/better fix is adding `flex-shrink: 0` to the sidebar styles.
