### ISSUE TITLE
Dummy App Setup- add ember-cli-addon-docs

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#38]
The dummy app in the addon should be used to document and demonstrate the flexibility of the components in this addon, within the different website contexts. 

- [ ] create a route for each site that we initially intend to support with this addon: 
- emberjs.com 
- ember-cli.com
- ember-engines.com
- ember-fastboot.com
- [ ] scope site-specific styles in the dummy app stylesheet
- [ ] add the navbar and footer to the application template
- [ ] add the data to the app data folder
- [ ] file issues for places where the components didn't separate concerns correctly

**Comment by josemarluedke** [comment]
To accomplish the above, one could use [ember-cli-addon-docs](https://github.com/ember-learn/ember-cli-addon-docs) project to write documentation and demo all the components available here.

**Comment by hakilebara** [comment]
I agree with @josemarluedke, I think ember-cli-addon-docs would be the right tool to organize the style-guides.
Today the style-guides' dummy app is a little confusing to navigate. I propose the following layout for the navbar. Each section would contain components and styles specific to a website/app.  @MelSumner what do you think?

![image](https://user-images.githubusercontent.com/1991564/41645732-257f0f3a-7472-11e8-90bd-34dca2dc045f.png)

**Comment by MelSumner** [comment]
@hakilebara I like this idea!

**Comment by ppcano** [comment]
If [ember-cli-addons-doc](https://ember-styleguide.netlify.com/) has replaced the `dummy-app`, could this issue be closed or there is still any pending work?

**Comment by MelSumner** [comment]
Yes, you're right! Thanks!
