### ISSUE TITLE
Add styles for inline code examples

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#380]
Currently we rely on https://github.com/empress/ember-showdown-prism for larger code blocks in our markdown e.g.

```
Things that look like this
```

That functionally works great but it doesn't provide any styles for **inline** code examples `like this` (using one backtick to surround the text) 

## Todo

- come up with exact styles for these inline code examples that work with the new design
- make sure it uses the correct monospace font 
- add an example to the Markdown example docs to make sure we have it documented https://github.com/ember-learn/ember-styleguide/blob/master/docs/concepts/markdown.md

**Comment by jenweber** [comment]
Sample CSS (this is close to what we use today):

```
code:not([class*="language-"]) {
    background-color: var(--color-gray-400);
    border-radius: 3px;
    font-size: .9em;
    padding: .2em .5em;
    margin: 0 .1em;
}
```

The problem with this is that the contrast between the graphical element and the light grey site background is too low. Right now, there is no contrast at all, so this is still a step in the right direction, but it needs one more iteration after this. Recommendations welcome!
