### ISSUE TITLE
Component: es-button

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#4]
**Context:**
The addon needs a consistent button element that covers the correct range of button needs. The button component already exists, but needs some more work.

**Needs:**
- [ ] should be an HTML button element
- [ ] should have a primary, secondary and tertiary version
- [ ] should have a solid design and outline design version
- [ ] should allow for an icon (font-awesome icon)
- [ ] should have hover,  focus and click design
- [ ] should support aria-pressed but should not render the aria-* tag unless required
- [ ] should support sizes (small, medium, large)
- [ ] should support mobile-first responsive web design (RWD)

**Screenshots:** 
![image](https://user-images.githubusercontent.com/4587451/35194740-d7167190-fe7d-11e7-8522-3a73bb05572f.png)

![image](https://user-images.githubusercontent.com/4587451/35194746-e4359dba-fe7d-11e7-8dc3-fb4228c1497a.png)

**Comment by pbishop16** [comment]
@MelSumner Would like to tackle this.

**Comment by MelSumner** [comment]
Lovely! Please visit https://codepen.io/melsumner/pen/9d551738a81e319a773395a2cfa1a82e/ and look for the button and icon button elements that have been gathered there so far.

**Comment by pbishop16** [comment]
@MelSumner Quick question, what dimensions do you want for the various button sizes?

**Comment by MelSumner** [comment]
@pbishop16 you can look at the css in the codepen and use that, it's accurate.

**Comment by pbishop16** [comment]
@MelSumner Oh yeah, I definitely have been referencing it. Sorry about the unclear question. I was a bit confused. I was not sure if you needed definitive small, medium and large button sizes as listed in the needs. No worries, I will just stick with what's outlined in the codepen. Thank you.

**Comment by rwwagner90** [comment]
You guys got this one under control?

**Comment by pbishop16** [comment]
@rwwagner90 Sure do. Just submitted a well overdue PR. Thank you for reaching out. If you have a moment, please let me know if you have any concerns.

**Comment by rwwagner90** [comment]
Merged, thanks a ton @pbishop16! Would love your help on more of these, if you have the cycles 😃
