### ISSUE TITLE
Component: es-heading

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#5]
**Context:**
Support is needed for h1-h6 heading elements. 

**Needs:**
- [ ] should support adding h1 to h6 for the tagName
- [ ] should support uppercase styling
- [ ] should support page title and section title (classes?)
- [ ] ensure that appropriate default sizes exist
- [ ] support mobile-first responsive web design (RWD)

**Comment by pbishop16** [comment]
@MelSumner I would like to tackle this.
