### ISSUE TITLE
Update to ember-fontawesome

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#50]
Add ember-fontawesome to be used for icons. https://github.com/FortAwesome/ember-fontawesome

**Comment by Dan-Ste** [comment]
But it's already added
https://github.com/ember-learn/ember-styleguide/blob/45d56bb5a39c5e1eb3252f4e5c2a8c164d1f75c0/package.json#L51

**Comment by MelSumner** [comment]
You're right! I've updated the issue- to update the version used. Thank you!

**Comment by Dan-Ste** [comment]
I've started working on this ticket and then realized that we use ember-font-awesome and ember-svg-jar simultaneously. Should we stick with one of them or continue to use both?

**Comment by Dan-Ste** [comment]
I think that ember-svg-jar is better choice because we can use not only font-awesome icons but any svg icons. Also there is more control over them.

**Comment by abhilashlr** [comment]
+1 for ember-svg-jar over font-awesome.

**Comment by MelSumner** [comment]
https://fontawesome.com/how-to-use/on-the-web/using-with/ember Putting this here so I can remember to do it.

**Comment by prasannavijayan** [comment]
@MelSumner I will work on this issue.
