### ISSUE TITLE
Remove all bootstrap references that are not ember-bootstrap

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#51]
when ember-bootstrap was added, the original bootstrap stuff wasn't removed, and that's causing issues. 

Hunt these instances down and remove all traces.

**Comment by Dan-Ste** [comment]
@rwwagner90 merging bootstrap into the tree is required for ember-boostrap?
https://github.com/ember-learn/ember-styleguide/blob/master/index.js

**Comment by rwwagner90** [comment]
@Dan-Ste it was required because we did not want to import all of ember-bootstrap. We were just using it for the navbar and it needed some hacks. To my knowledge, we're not using any bootstrap other than ember-bootstrap. @MelSumner where are the other bootstrap things you are seeing?

**Comment by Dan-Ste** [comment]
@rwwagner90 We still need these hacks for some reasons which I don't understand
