### ISSUE TITLE
Styles: Prefer to apply styles with classNames over raw HTML tagNames

### ISSUE THREAD

**Issue by localpcguy** [ember-learn/ember-styleguide#53]
## Expected Behavior
When reading or adding styles for a component, I would expect to see styling applied via classNames rather than raw tag references (i.e. `li` vs. a class attribute on that `li`).

## Actual Behavior
Styles include references to raw tags

## Proposed solution
I propose that all new components be written using classNames for styling hooks, rather than attaching styles to raw tag names. We could check this in new PRs to ensure this style is maintained for new code going forward and should work to update existing styles to maintain this style for components that already exist.

**Comment by localpcguy** [comment]
I'm happy to take this one

**Comment by MelSumner** [comment]
How about we close this ticket out and open one for each component that needs this change? That way it will be more actionable. :+1:
