### ISSUE TITLE
Component: es-footer refactor

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#56]
## Expected Behavior
The data should be separate from the component. The data is an application concern. The footer component itself shouldn't care. 

## Actual Behavior
The current footer component is only the emberjs.com website footer.

**Comment by cdvillard** [comment]
It doesn't look like anyone has taken this on, and I might actually have some downtime to handle this so I'd like to tackle it if I may? I'm also the one who took on the footer in the first place, so my bad.

**Comment by MelSumner** [comment]
@cdvillard I didn't give explicit enough guidance in the first component, so it's not your fault at all. 

Please make this one es-pagefooter that way we can discuss with everyone who is already using the es-footer component to replace.

**Comment by MelSumner** [comment]
Opening this back up for other contributors to work on as well.

**Comment by ppcano** [comment]
@MelSumner I can look at this one, any other requirement besides moving the existing template info to support the data to be a component parameter.

**Comment by spruce** [comment]
Can't this be closed as of #89 ?
