### ISSUE TITLE
Move styles from addon/styles to app/styles

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#59]
In order for the addon's styles to be correctly rendered in the application, the styles need to be in the app/styles folder. 

There are more complex ways of dealing with this, but this is a straightforward route.

**Comment by MelSumner** [comment]
I'm marking this one blocked for now because we've discovered some other issues with the theme-changer. so until those are resolved we'll leave the styles where they are.

**Comment by localpcguy** [comment]
@MelSumner If updating multiple style files (re: #54), which set should be considered the ones to change? I'm assuming `addon/styles` for the time being, but there are currently differences between the two folders.

**Comment by localpcguy** [comment]
I ended up updating the `app/styles` with the styles from `addon/styles` as part of PR #101 (for #54). There weren't that many differences, but if anything in `app/styles` should be the most recent we may need to check in the history to grab it once that PR is merged.

**Comment by MelSumner** [comment]
It looks like the styles are now in both addon/styles and app/styles which is the least desirable thing we could be doing.

**Comment by MinThaMie** [comment]
Discussed with @mansona and this is no longer accurate
