### ISSUE TITLE
Aliasing Issues on Headers

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#63]
The Headers currently look like this: 
![screen shot 2018-06-04 at 20 01 39](https://user-images.githubusercontent.com/594890/40936123-32e2b704-6832-11e8-9adc-bd32b1172473.png)

and when you add the following rule: 

```
h1 {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale
}
```

they look like this: 
![screen shot 2018-06-04 at 20 02 56](https://user-images.githubusercontent.com/594890/40936148-512aff32-6832-11e8-924b-9e7daf651bb5.png)

It is quite subtle with the Font Roboto but when the headers were using the wrong font it was **very** obvious. I don't know if this is even needed now that it's using the right font 🤔

**Comment by nummi** [comment]
I can't really tell the difference except for _very_ subtle gray aliasing. Do we really want that?

**Comment by mansona** [comment]
@nummi it is less subtle with other fonts, for example before I fixed the headers using Roboto it looked like this: 

![screen shot 2018-06-04 at 19 42 12](https://user-images.githubusercontent.com/594890/40961967-182ea372-689c-11e8-8cdd-77c2945b7e3c.png)

This does look pretty bad and anyone with a design eye would likely judge us for this, especially when this is used on the homepage 😖

**Comment by nummi** [comment]
Where do we use Alegreya Sans? I thought Roboto was the correct font?

**Comment by MelSumner** [comment]
@nummi we don't- we considered it for a while and there was just an outdated variable value in this code. (we were trying to find a good complementary header font to pair with Roboto) 

@mansona you could put these properties in the addon/styles/addon.scss file: 

```
h1, h2, h3, h4, h5, h6 {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale
}
```
