### ISSUE TITLE
Component: es-cta

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#7]
**Context:**
The call-to-action(CTA) component can be used in any place where a CTA is desired. The content and button will be stacked on small viewports, but side by side on large viewports. If the text is too long, it will wrap. On a small viewport it will take up 95% of the viewport. On larger viewports, it will be contained to 85%.

**Acceptance Criteria:**
- [ ] component name should also be the class name attached to the component (via classNames)
- [ ] ensure this works as intended on IE, Firefox and Chrome
- [ ] ensure CSS is scoped to component, and written in a mobile-first way
- [ ] ensure the text content and button is stacked on small viewports, but side by side on larger viewports.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/4587451/35194701-14571006-fe7d-11e7-97c5-40f85123caca.png)

![image](https://user-images.githubusercontent.com/4587451/35194713-539f0c96-fe7d-11e7-89ab-ee52b840fb28.png)

**Comment by rwwagner90** [comment]
This seems like something I could tackle. Do we have examples of this used in current docs?

**Comment by MelSumner** [comment]
@rwwagner90 yes - example would be if you visit an old page of the guides, there's a message that tells you that you're viewing the old guides, and gives you a link to the new guides (in that button).

**Comment by MelSumner** [comment]
@rwwagner90 is there anything I can do to help this move forward?

**Comment by rwwagner90** [comment]
Hi @MelSumner nothing in particular. When I was moved to Ember Inspector work, a lot of my in progress things from just the general learning team side of things fell by the wayside. I'll try to get back into working on this stuff more soon.

**Comment by qpowell** [comment]
@rwwagner90 Do you care if I take this one off your plate?

**Comment by rwwagner90** [comment]
@qpowell go for it! I'm swamped with work and ember-inspector things at the moment.

**Comment by MelSumner** [comment]
We should also work on an updated design for this component that works with the website re-design.

**Comment by MinThaMie** [comment]
AFAIK there are no CTA's currently in our design, so let's close this issue and make a new one when we actually need it.
