### ISSUE TITLE
bug: h3 elements with code in them have overlapping lines, line height is too low

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-styleguide#94]
## Expected Behavior
Multiple lines of text should not overlap. To fix this, you could either tighten the padding in the code highlighting block (make sure it doesn't cut off the ends of long letters like y and g), or increase line height of h3 elements.

## Actual Behavior
![screen shot 2018-09-29 at 6 34 17 pm](https://user-images.githubusercontent.com/16627268/46251062-b3394680-c416-11e8-8b1a-3f16b8d28b21.png)

## Steps to Reproduce

Here's an example [from the Guides](https://guides.emberjs.com/release/components/the-component-lifecycle/#toc_lifecycle-hook-examples).

Here's the markdown:
```
<h3 id="toc_resetting-presentation-state-on-attribute-change-with-didupdateattrs" class="anchorable-toc">
    Resetting Presentation State on Attribute Change with 
   <a class="toc-anchor" href="#toc_resetting-presentation-state-on-attribute-change-with-didupdateattrs">
   </a>
   <code>didUpdateAttrs</code>
</h3>
```

**Comment by MelSumner** [comment]
Resolved! :+1:
