### ISSUE TITLE
Component: es-aside

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#99]
Create an es-sidebar-menu component. Could be named differently if we think of something more concise/elegant. 

Requirements: 
- should not be inside of the aside element (we may wish to put other things in the sidebar- this component should just be the menu portion. 
- should use semantic HTML 
- should be keyboard navigable for users with assistive technology
    - TAB should take the user to the menu
    - ARROW UP and DOWN keys should move them within the list
    - ENTER or SPACE should expand/collapse sections to reveal/hide subsections
- should look like the current sidebar in the guides (see screenshot below)

Screenshot: 
![image](https://user-images.githubusercontent.com/4587451/46362039-d93c3200-c634-11e8-9d57-939bc1f47403.png)

**Comment by ppcano** [comment]
I plan to work on this issue soon,  based on the API proposal commented at #91 

```
{{#es-aside as |f|}}

  {{#f.header}}
    Optional header
  {{/f.header}}

  {{#f.category open=(eq currentSection.id page.id) as |p|}}
    {{#p.title}}
      Getting started
    {{/p.title}}
    {{#p.option}}
      {{#link-to ''}}
        Quick start
      {{/link-to}}
    {{/p.option}}
    {{#p.option}}
      {{#link-to ''}}
        Installing Ember
      {{/link-to}}
    {{/p.option}}
  {{/f.category}}

  {{#f.category as |p|}}
    {{#p.title}}
      Deprecations added in 2.3
    {{/p.title}}
    {{#p.option}}
      <a href="#toc_non-primitive-defaultvalue-for-model-attributes">
        Non-primitive defaultValue for Model Attributes
      </a>
    {{/p.option}}
  {{/f.category}}

  {{#f.footer}}
    Optional footer
  {{/f.footer}}


{{/es-aside}}
```

**Comment by MinThaMie** [comment]
We'll create a new issue to port [this menu](https://github.com/ember-learn/guidemaker-ember-template/pull/98) to the style guide when it's ready
